version: '3.8'

networks:
  unitrade-net:
    driver: bridge

services:
  web:
    image: odoo:17.0 # Pembaruan mutlak ke Odoo 17
    depends_on:
      - db
    ports:
      - '8069:8069'
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - unitrade-net

  mailpit:
    image: axllent/mailpit
    container_name: unitrade_mail
    ports:
      - '8025:8025' # Port untuk melihat email di browser
      - '1025:1025' # Port SMTP untuk komunikasi dengan Odoo
    networks:
      - unitrade-net

  db:
    image: postgres:15
    
    ports:
    - "5432:5432"

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - unitrade-net

  # JALUR 2: Panel pgAdmin berbasis Web (Tinggal buka via browser VPS)
  pgadmin:
    image: dpage/pgadmin4
    container_name: unitrade_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@unitrade.web.id # Email untuk login ke web pgAdmin
      PGADMIN_DEFAULT_PASSWORD: masbahlilganteng # Password untuk login ke web pgAdmin
    ports:
      - '8050:80' # Akses pgAdmin via browser di port 8050
    depends_on:
      - db
    networks:
      - unitrade-net

  # Mesin pekerja sementara untuk merender Tailwind CSS
  frontend-builder:
    image: node:lts
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build"
    networks:
      - unitrade-net

volumes:
  odoo-web-data:
  odoo-db-data:
