{
    'name': 'UniTrade Notification',
    'version': '17.0.1.0.0',
    'summary': 'System notifications for orders, payments, and deliveries',
    'author': 'Tim 1 - UNISA Yogyakarta',
    'category': 'Website',
    'depends': [
        'mail',
        'auth_signup',
        'unitrade_theme',
        'unitrade_seller',
        'unitrade_payment',
        'unitrade_delivery',
        'unitrade_chat',
        'unitrade_review',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/notification_security.xml',
        'data/ir_config_parameter.xml',
        'data/ir_cron.xml',
        'data/mail_template.xml',
        'views/notification_templates.xml',
        'views/notification_admin_views.xml',
        'views/announcement_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'unitrade_notification/static/src/scss/notification.scss',
            'unitrade_notification/static/src/js/notification_service.js',
            'unitrade_notification/static/src/js/notification_bell.js',
            'unitrade_notification/static/src/xml/notification_bell.xml',
        ],
    },
    'installable': True,
    'license': 'LGPL-3',
}
