{
    'name': 'UniTrade Theme',
    'version': '17.0.1.0.0',
    'summary': 'UniTrade Marketplace Theme with Tailwind CSS',
    'description': """
        Custom theme for UniTrade C2C Marketplace.
        - Tailwind CSS with tw- prefix
        - Custom QWeb templates
        - Storefront homepage
        - Responsive layout
    """,
    'author': 'Tim 1 - UNISA Yogyakarta',
    'website': 'https://unitrade.dev',
    'category': 'Website/Theme',
    'depends': ['website', 'website_sale', 'website_sale_stock', 'portal', 'auth_signup', 'auth_oauth'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/unitrade_config.xml',
        'data/oauth_provider.xml',
        'data/checkout_fee_product.xml',
        'data/customer_ticket_sequence.xml',
        'views/sponsorship_views.xml',
        'views/templates.xml',
        'views/navbar_templates.xml',
        'views/product_card_templates.xml',
        'views/homepage.xml',
        'views/shop_templates.xml',
        'views/product_templates.xml',
        'views/snippets.xml',
        'views/legal_templates.xml',
        'views/contact_templates.xml',
        'views/login_templates.xml',
        'views/otp_templates.xml',
        'views/profile_templates.xml',
        'views/seller_verification.xml',
        'views/cart_templates.xml',
        'views/checkout_templates.xml',
        'views/sponsorship_templates.xml',
        'views/customer_service_templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'unitrade_theme/static/src/css/output.css',
            'unitrade_theme/static/src/css/legal.css',
            'unitrade_theme/static/src/css/contact.css',
            'unitrade_theme/static/src/xml/shop_filter.xml',
            'unitrade_theme/static/src/xml/product_detail.xml',
            'unitrade_theme/static/src/xml/orders.xml',
            'unitrade_theme/static/src/xml/logout_confirm.xml',
            'unitrade_theme/static/src/xml/customer_service.xml',
            'unitrade_theme/static/src/js/logout_confirm.js',
            'unitrade_theme/static/src/js/main.js',
            'unitrade_theme/static/src/js/legal.js',
            'unitrade_theme/static/src/js/contact.js',
            'unitrade_theme/static/src/js/shop_filter.js',
            'unitrade_theme/static/src/js/product_detail_owl.js',
            'unitrade_theme/static/src/js/product_detail.js',
            'unitrade_theme/static/src/js/profile.js',
            'unitrade_theme/static/src/js/orders.js',
            'unitrade_theme/static/src/js/customer_service.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
